name: examples
version: 0.0.1
description: Example
repository: https://github.com/faithoflifedev/yt
homepage: https://github.com/faithoflifedev/yt
publish_to: none

environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:
  googleapis: ^10.1.0
  googleapis_auth: ^1.4.0
  lints: ^2.0.1
  yaml: ^3.1.1
  yt:
    path: ../../yt
