name: example
version: 0.0.1
description: Example
repository: https://github.com/faithoflifedev/yt
homepage: https://github.com/faithoflifedev/yt
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  lints: ^1.0.1
  yt:
    path: /Users/chris/projects/skc/broadcast/yt
