name: examples
version: 0.0.1
description: Example
repository: https://github.com/faithoflifedev/yt
homepage: https://github.com/faithoflifedev/yt
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  lints: ^2.1.1
  yaml: ^3.1.2
  yt:
    path: ../../yt
