name: examples
version: 0.0.1
description: Example
repository: https://github.com/faithoflifedev/yt
homepage: https://github.com/faithoflifedev/yt
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  googleapis: ^9.1.0
  googleapis_auth: ^1.3.1
  lints: ^2.0.0
  yaml: ^3.1.0
  yt:
    path: ../../yt
