name: yt
version: 2.2.5+3
description: Native Dart interface to multiple YouTube REST APIs including the Data API.
repository: https://github.com/faithoflifedev/yt
homepage: https://github.com/faithoflifedev/yt

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  args: ^2.4.2
  csv: ^5.1.1
  dio: ^5.4.0
  fling_pickle: ^0.4.3
  googleapis_auth: ^1.4.1
  http: ^1.2.0
  http_parser: ^4.0.2
  json_annotation: ^4.8.1
  loggy: ^2.0.3
  retrofit: ^4.0.3
  stemmer: ^2.2.0
  universal_io: ^2.2.2
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.8
  cli_pkg: ^2.7.2
  grinder: ^0.9.5
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  lints: ^3.0.0
  pub_semver: ^2.1.4
  publish_tools: ^0.1.0+15
  pubspec: ^2.3.0
  retrofit_generator: ^8.0.6

executables:
  yt:
