name: yt
version: 1.2.2
description: Native Dart interface to multiple YouTube REST APIs including the Data API, Live Streaming API and Cloud Vision API.
repository: https://github.com/faithoflifedev/yt
homepage: https://github.com/faithoflifedev/yt

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.0
  color: ^3.0.0
  crypto_keys: ^0.3.0
  csv: ^5.0.1
  dartz: ^0.10.1
  dio: ^4.0.4
  image: ^3.1.0
  easy_enum: ^1.0.0
  fling_pickle: ^0.4.0
  http_parser: ^4.0.0
  jose: ^0.3.2
  json_annotation: ^4.4.0
  process_run: ^0.12.3+1
  retrofit: ^3.0.0
  simple_mustache: ^2.1.0
  stemmer: ^2.2.0
  universal_io: ^2.0.4
  dio_cache_interceptor: ^3.2.6
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.7
  easy_enum_generator: ^2.0.2
  grinder: ^0.9.0
  json_serializable: ^6.1.3
  lints: ^1.0.1
  # mustache_template: ^2.0.0
  retrofit_generator: ^4.0.1

executables:
  yt:
