templates:
  - name: README.md
    type: overwrite
  - name: CHANGELOG.md
    type: prepend

version: 1.1.0
change: video upload actually works, refactored thumbnail upload and added support for the VideoCategories API
